[package]
name = "xtask"
version = "0.1.0"
authors = ["Sean Lyons <seanmlyons22@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tixml2svd = "0.1.4"
svd2rust = "0.33.1"
form = "0.12.1"