#[doc = "Register `FSCR` reader"]
pub type R = crate::R<FscrSpec>;
#[doc = "Register `FSCR` writer"]
pub type W = crate::W<FscrSpec>;
#[doc = "Field `FSCR` reader - 31:0\\]
The global synchronization trigger is generated by the Program Counter (PC) Sampler block. This means that there is no synchronization counter in the TPIU."]
pub type FscrR = crate::FieldReader<u32>;
impl R {
    #[doc = "Bits 0:31 - 31:0\\]
The global synchronization trigger is generated by the Program Counter (PC) Sampler block. This means that there is no synchronization counter in the TPIU."]
    #[inline(always)]
    pub fn fscr(&self) -> FscrR {
        FscrR::new(self.bits)
    }
}
impl W {}
#[doc = "Formatter Synchronization Counter\n\nYou can [`read`](crate::generic::Reg::read) this register and get [`fscr::R`](R).  You can [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`write_with_zero`](crate::generic::Reg::write_with_zero) this register using [`fscr::W`](W). You can also [`modify`](crate::generic::Reg::modify) this register. See [API](https://docs.rs/svd2rust/#read--modify--write-api)."]
pub struct FscrSpec;
impl crate::RegisterSpec for FscrSpec {
    type Ux = u32;
}
#[doc = "`read()` method returns [`fscr::R`](R) reader structure"]
impl crate::Readable for FscrSpec {}
#[doc = "`write(|w| ..)` method takes [`fscr::W`](W) writer structure"]
impl crate::Writable for FscrSpec {
    type Safety = crate::Unsafe;
    const ZERO_TO_MODIFY_FIELDS_BITMAP: u32 = 0;
    const ONE_TO_MODIFY_FIELDS_BITMAP: u32 = 0;
}
#[doc = "`reset()` method sets FSCR to value 0"]
impl crate::Resettable for FscrSpec {
    const RESET_VALUE: u32 = 0;
}
